version: '3.8'

services:
  api:
    image: api-docker
    ports:
      - "2443:80"
    depends_on:
      - sqlDock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=sqlDock,1433;Initial Catalog=dddDb;Persist Security Info=True;User ID=sa;Password=Dockersql123!;TrustServerCertificate=true;

  sqlDock:
    container_name: sqlDock   # Make sure the container name is specified
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Dockersql123!
      - ACCEPT_EULA=Y

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2080:80"

networks:
  default:
    driver: bridge
